### PR TITLE
Ability to set 0 value and see which value actually got applied

### PR DESCRIPTION
**Pull request by Falcosc**
Some limits like psi0soc were 0 on my platform, so it would be nice to be able to set them back to 0.

### CODE REVIEW

**Comment by FlyGoat** [comment]
How can you initialize uint32_t to -1....

**Comment by FlyGoat** [comment]
Also I believe internal code should not be exposed via posix returning.
It's possible to have multiple errors at the same time and a single error code won't cover them all.
We just return -1 to indicate error happens and rely on prints to tell users what happens.

**Comment by Falcosc** [comment]
I did remove the error code exposing

And I did add one more comment to make this more clear for others. I was not sure if you would like a comment there because I thought such value overflow tricks are common practices and don't need explanation like the incompatible type castings tricks from string to uint in the argparse methods :)

**Comment by FlyGoat** [comment]
Thanks.

**Pull request merged**
