### PR TITLE
add: Load previous settings via settings file (UI) + Exit button (UI)

### PR DESCRIPTION
**Pull request by EnumC**
This PR contains the following update:

* Add:
   - loadSettings () method
   - Exit button

* Modify:
   - Select UI Text
   - Save file location/filename
   - RunExe() return type
   - Remove exit statement after applying settings
   - Renames apply button handler method

* Test cases:
   - Nonexistent settings file
   - Settings file with missing arguments
   - Settings with populated arguments

### CODE REVIEW

**Comment by FlyGoat** [comment]
Could you please provide a binary for test?
Thanks a lot.

**Comment by EnumC** [comment]
[Debug.zip](https://github.com/FlyGoat/RyzenAdj/files/2888754/Debug.zip)
@FlyGoat Here you go.

**Comment by EnumC** [comment]
Oops. There's a minor oversight in the loadSettings() method as I did not remove the trailing "000"s. I'll push a commit to fix that asap.

**Comment by EnumC** [comment]
[Debug_fix.zip](https://github.com/FlyGoat/RyzenAdj/files/2888857/Debug_fix.zip)
@FlyGoat Here's the fixed copy which correctly removes the last 3 trailing 0s.

**Pull request closed without merging**
