### PR TITLE
Memory support without Interface change

### PR DESCRIPTION
**Pull request by Falcosc**
Suggestion to get the PTable interface change pullrequest smaller.

### CODE REVIEW

**Comment by FlyGoat** [comment]
Please rebase, I may take this part first :-)

**Comment by Falcosc** [comment]
done

**Comment by Falcosc** [comment]
@jnsquire did the Linux testing. It does work good great as long as you don't do silly things like 26 context switches in a split second. 
After changing from 4 byte small requests to a table cache inside ryzen_access this memory function seems to work fine.

**Comment by Falcosc** [comment]
@jnsquire did told me that a page is 4k. So that is the issue in our mmap function.

It does only work if SMU will give us an aligned memory address.

**Pull request merged**
