### PR TITLE
New command - "-z" "--infonew". More information in info command

### PR DESCRIPTION
**Pull request by Erruar**
# More information in information table
image
image
image

### CODE REVIEW

**Comment by Falcosc** [comment]
Thank you,

I don't like having a 2nd Info command, since it is hard to communicate the difference: nobody reads documentation, so all differences have to be somehow self explaining, which I have no idea how to achieve.

If reasons for having a 2nd command are difficult to communicate, why not extending the old command to avoid the problem of communication?

I don't care if the Info command gets slower by more requests.

**Comment by FlyGoat** [comment]
Thanks @Falcosc that's my opinion as well.

Also these functions need to be in ryzenadj public API.

**Comment by Erruar** [comment]
##### Falcosc
`I don't like having a 2nd Info command, since it is hard to communicate the difference: nobody reads`

I understand perfectly well that it is better to implement all this in one team, but since so many different projects use ryzenadj it will be better to create a different one command to not broke user algorithms for old command. In the future, you can combine everything into one. In addition, support for some processors is still being finalized, so I did not remove the old command. Thanks for understanding

**Comment by Falcosc** [comment]
Nobody should parse command results.

We should reformat the console output from time to time to remind people to use the API instead of parsing command output.

So don't care about the command output, you can rearrange everything :)

**Comment by Erruar** [comment]
#### @Falcosc 
`because they use the command line as API instead of using our API`

Thats true.
So your decision is to replace an existing command ("-i, --info") to obtain information instead of creating a new one?

**Comment by Erruar** [comment]
SMU Really can be locked by a lot of calls in one time and system will behave so weird or even crash. Yes, we need to minimise calls

**Comment by Falcosc** [comment]
Just put your code between the existing code instead of reinventing the wheel :)

Maybe there is something missing in your code, or we have bugs in the old code. Just another benefit of merging the code together. So don't just remove it, build your code lines into the old code lines to find bugs in the old code or to find some little things you didn't think of.

And check if anything needs to be exposed in the API, I didn't check your code in detail, because it will look different after you merged it into the old one anyway.

**Comment by Erruar** [comment]
My tester have tested it on Rembrandt laptop CPU and indexes are not same. Need to rework on this platform. Other CPUs are working fine. Z1/Z1 extreme are not supported. Okay. I'll put it into one old command

**Comment by Falcosc** [comment]
I don't care about the old code, just analyze it by trying to put your features into the old code to learn from each other. If it needs to be removed because incompatible with your concept, it's fine for me.

I would appreciate it if you tell us if you found bugs in the old code. Just don't want to have a blind remove since it already got through multiple years of testing by thousands of users. Would be a waste to not learn from it.

**Comment by Erruar** [comment]
I'm one of the few developers who really understands Ryzens, SMUs, registers, etc., so I want to contribute to this project too

**Comment by Erruar** [comment]
I will finalize as you said and create a new pull request

**Comment by Falcosc** [comment]
Don't focus too much on the "reduce commands" topic
If the info parameter uses many of them, it is ok, we don't need a small and a large info one for everything is enough. Because info should only be used if a human interacts with CLI.

For applications, the developer can decide which data is needed. To avoid developers using our info command, we did even provide examples for how to get any data extracted out of the table over our API without using the info CLI :)
Just wanted to give a reason why there is a risk of using our CLI as API and why we should not care about stable CLI output, since it's humans first.

**Pull request closed without merging**
